# Файл docker-compose.yml

# Версия docker-compose
version: '3'

# Перечень volume
volumes:
  pg_data_production:
  static_volume:

# Перечень контейнеров
services:
  # Имя и описание первого контейнера; имя выбирает разработчик.
  # Это контейнер БД
  db:
    # Из какого образа запустить контейнер:
    image: postgres:13.10
    # Файл (или список файлов) с переменными окружения
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  # Имя и описание контейнера с бэкендом
  backend:
    # Из какого Dockerfile собирать образ для этого контейнера:
    image: anawesomewave/taski_backend:latest
    env_file: .env
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
      # Имя третьего контейнера. Это контейнер с фронтендом
  frontend:
    env_file: .env
    image: anawesomewave/taski_frontend:latest
    volumes:
      - static_volume:/frontend_static
    command: cp -r /app/build/. /frontend_static/
  gateway:
    image: anawesomewave/taski_getaway:latest
    volumes:
      - static_volume:/staticfiles
    ports:
      - 8000:80